[package]
name = "elint"
version = "0.0.1"
edition = "2024"
rust-version = "1.96"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
license = "MIT"
description = "Erlang code linter"
homepage = "https://github.com/sile/elint"
repository = "https://github.com/sile/elint"
readme = "README.md"

[dependencies]
erl_tokenize = "0.11"
erl_pp = "0.4"
erl_parse = "0.3"
noargs = "0.4.3"
