[package]
name = "elint"
version = "0.0.1"
edition = "2024"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
license = "MIT"
description = "Erlang code linter"
homepage = "https://github.com/sile/elint"
repository = "https://github.com/sile/elint"
readme = "README.md"

[dependencies]
erl_tokenize = "0.10.0"
noargs = "0.4.2"
nojson = "0.3.6"
orfail = "2.0.0"
